version = 0.1

# ─── Production ───────────────────────────────────────────────────────────────
[default.deploy.parameters]
stack_name = "delta-app-prod"
# resolve_s3 = true
s3_prefix = "delta-app-prod"
s3_bucket = "delta-sam-artifacts-prod"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
# After Phase 2 deploy, replace the empty strings with real CloudFront values:
parameter_overrides = "ENVIRONMENT=\"Prod\" ServicePrefix=\"delta-prod\" TableName=\"prod_delta_releases\" S3BucketName=\"app-ota-release\" CloudFrontIDS=\"E1AUTHN8OHPKGU\" DeltaCloudFrontURL=\"https://d1gayior9t3avn.cloudfront.net/\""
#parameter_overrides = "ENVIRONMENT=\"Prod\" ServicePrefix=\"delta-prod\" TableName=\"prod_delta_releases\" S3BucketName=\"app-ota-release\" CloudFrontIDS=\"\" DeltaCloudFrontURL=\"\""
image_repositories = []

# ─── Staging ──────────────────────────────────────────────────────────────────
[staging.deploy.parameters]
stack_name = "delta-app-staging"
# resolve_s3 = true
s3_bucket = "delta-sam-artifacts-staging-1"
s3_prefix = "delta-app-staging"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
# Phase 2 — CloudFront + API Gateway values populated from stack outputs
#parameter_overrides = "ENVIRONMENT=\"staging\" ServicePrefix=\"delta-staging\" TableName=\"staging_delta_releases\" S3BucketName=\"app-ota-release-staging\" CloudFrontIDS=\"\" DeltaCloudFrontURL=\"\""
parameter_overrides = "ENVIRONMENT=\"staging\" ServicePrefix=\"delta-staging\" TableName=\"staging_delta_releases\" S3BucketName=\"app-ota-release-staging\" CloudFrontIDS=\"E3OJCI7XKYYGEA\" DeltaCloudFrontURL=\"https://d1kvd01i9ysk40.cloudfront.net/\" ApiGatewayIdss=\"ni57ilt93f\""
image_repositories = []
